# Generated by Django 4.2.2 on 2023-10-01 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='User',
            new_name='user',
        ),
    ]
